### ISSUE TITLE
Créer un serveur ?

### ISSUE THREAD

**Issue by MadDog84** [DaweedM/chimboland-nio-server#1]
Salut ! Je suis un ancien de chimboz et j'ai voulu créer un serveur juste pour moi pour revoir tout ça !

J'aimerai savoir comment on fait ? Je sais faire un site avec wamp mais aucune idée de comment executer un serveur java ?

Merci :)

**Comment by daweedm** [comment]
Salut,

Il s'agit ici du serveur tchat uniquement

**Comment by MadDog84** [comment]
Ah mince d'accord desolé ! Impossible de mettre la main sur le serveur entier :-(
