### ISSUE TITLE
Problème de compilation (sous JDK7)

### ISSUE THREAD

**Issue by chimbozzy** [DaweedM/chimboland-nio-server#2]
Sur le GitHub, sauf erreur de ma part, ne se trouve pas de note précisant les lib à ajouter (si il y a), la version java à utiliser.

Lors de la compilation en JDK7, plusieurs erreurs surviennent : 

`java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.chimboland.tchat.ChimbolandNIO.run(ChimbolandNIO.java:167)
        at org.chimboland.tchat.Chimboland.main(Chimboland.java:12)
`

**Comment by chimbozzy** [comment]
NOTE: L'erreur suivante `java.lang.ClassNotFoundException: com.mysql.jdbc.Driver at `
est lié à un lib de mysql-connector-java-x.x.x-bin qu'il suffit d'ajouter.

**Comment by daweedm** [comment]
Effectivement les libs utilisées sont un manquement à préciser dans le README.

Le driver officiel de MySQL pour Java est dispo en téléchargement ici : https://dev.mysql.com/downloads/connector/j/

Ensuite, il te suffit de l'ajouter en tant que dépendance dans ton IDE.
Sous Eclipse par exemple cela se passe dans : 
(clique droit sur) Project → Build Path → Configure Build Path puis Sous l'onglet "Libraries", cliquer sur Add External JARs et sélectionner le driver (voir https://stackoverflow.com/questions/3280353/how-to-import-a-jar-in-eclipse)

**Comment by chimbozzy** [comment]
Le mysql-connector est bien ajouté dans le build path.

Mais une fois le projet compilé et exporté en .jar, lorsqu'ont éxécute le .jar en invite de commande (précisément en .bat), ça revient sur l'erreur ci-dessus.
Peut-être loupé une étape ?

**Comment by daweedm** [comment]
Dans mes souvenirs lors de l'exportation en archive jar depuis eclipse, il te propose d'y inclure les dépendances (sans doute une checkbox), tu l'as sélectionnée ?

**Comment by chimbozzy** [comment]
J'ai inclus le dossier que j'ai nommé "lib" contenant le .jar de mysql-connector et le message reste le même quand j’exécute le serveur.. ce n'est sans doute le seul problème de mon côté à résoudre afin de réussir l’exécution du serveur :/

EDIT : Et pourtant quand je fait un test sous eclipse via "RUN" le serveur s’exécute normalement (avec quelques exceptions logique non gênante au bon fonctionnement), mais dès que je l’exécute avec le fichier .jar exporté je me retrouve avec l'erreur.

**Comment by chimbozzy** [comment]
Quand j’exécute directement dans eclipse j’obtiens un résultat réussit :
```
Le sauvetage des req. SQL importantes est operationnel.
[Exception][com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException]{sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method); sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source); sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source); java.lang.reflect.Constructor.newInstance(Unknown Source); com.mysql.jdbc.Util.handleNewInstance(Util.java:425); com.mysql.jdbc.Util.getInstance(Util.java:408); com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943); com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973); com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909); com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527); com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680); com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483); com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552); com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607); com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480); org.chimboland.tchat.ChimbolandNIO.Mysql_Query(ChimbolandNIO.java:591); org.chimboland.tchat.ChimbolandNIO.run(ChimbolandNIO.java:173); org.chimboland.tchat.Chimboland.main(Chimboland.java:12); }

Serveur Tchat Chimboland - Architecture New I/O
Windows 10 (amd64) - Java v1.8.0_151
2 processeurs disponibles : 5 Threads lances. (MAX. 6)
IP Locale : localhost - Port 5000
Path : /
En attente d'un client !
[Exception][java.sql.SQLException]{org.chimboland.tchat.ChimbolandNIO.Mysql_Query(ChimbolandNIO.java:600); org.chimboland.tchat.ChimbolandNIO.run(ChimbolandNIO.java:173); org.chimboland.tchat.Chimboland.main(Chimboland.java:12); }
```

Et dans la version exporté en .jar sous invite .bat : 
```
java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.chimboland.tchat.ChimbolandNIO.run(ChimbolandNIO.java:167)
        at org.chimboland.tchat.Chimboland.main(Chimboland.java:12)
```

**Comment by daweedm** [comment]
Pour le lancement depuis l'archive jar tu dois avoir un soucis de configuration, preuve qu'en lançant le programme depuis Eclipse tu arrives à charger le driver, je t'invite à faire quelques recherches sur le sujet sur le web, ne travaillant Windows je ne saurai pas t'aider :/

Pour l'autre erreur, le serveur chat était prévu pour fonctionner avec un schéma spécifique de la base de donnée (les sites chimboz ayant donné naissance à plusieurs forks du projet original), à mon avis le côté site avec lequel tu travailles n'est pas tout simplement pas compatible ... Ce que l'erreur te dit c'est que le programme essaie d'effectuer une requête avec une syntaxe erronée, à mon avis il essaie de travailler sur une table SQL qui n'existe pas ou possède un format différent dans ta version du site

**Comment by chimbozzy** [comment]
Effectivement Eclipse ne veut pas inclure le dossier LIB, malgré qu'il soit bien sélectionné dans la sortie build path..
Merci pour les informations à ce problème du driver je vais fouiller dans eclipse pour savoir pourquoi il ne veut pas me l'inclure ce dossier lib..

Merci
